name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo Hello Ramesh K P
      - name: Multiline Command
        run: | 
          python -V
          pip -V

  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers

  dependent-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo a string
        run: Write-Output "Workflow Course"
      - name: Error Step
        run: doesnotexistss
      

          