name: Workflow Commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing Docstring"

      - name: Setting an error message with parameters
        run: echo "::error title=Error Title, file=add.py, line=2, endLine=3, col=5, endCol=7::Missing Semicolomn"

      - name: Setting a debug message with parameters
        run: echo "::debug title=Debug Title, file=add.py, line=2, endLine=3, col=5, endCol=7::Missing Semicolomn"

      - name: Setting a warning message with parameters
        run: echo "::warning title=Warning Title, file=add.py, line=2, endLine=3, col=5, endCol=7::Missing Semicolomn"

      - name: Setting a notice message with parameters
        run: echo "::notice title=Notice Title, file=add.py, line=2, endLine=3, col=5, endCol=7::Missing Semicolomn"

      - name: Group of Logs
        run: |
          echo "::group::Group Title"
          echo "Inside Group"
          echo "::endgroup::"

      - name: Masking a Value
        run: echo "::add-mask::Ramesh"

      - name: Echo a Secret
        run: echo "Ramesh"
