name: Workflow Run
on:
  workflow_run:
    workflows: [First Workflow]
    types: [completed]

jobs:
  echo-string: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "I was triggered because 'First Workflow' was completed"


